language: python
python:
  - 2.7
  - 3.5
install:
  - pip install -U pip
  - pip install coveralls
script: coverage run --source=json2table -m unittest tests.test_json2table
after_success:
  coveralls
